apiVersion: v1
kind: Pod
metadata:
  name: unhealthy-express
  namespace: apps
  annotations:
    prometheus.io/scrape: "true"
spec:
  containers:
    - name: unhealthy-express
      ports:
        - containerPort: 80
      image: unhealthy-express:0.0.1
      imagePullPolicy: Never
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
        requests:
          cpu: "0.5"
          memory: "128Mi"
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 2
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 1
